/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Biolab4.glb -d 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lab(props) {
  const { nodes, materials } = useGLTF('/assets/2023-04-27/v007/BioLab4.glb')
  return (
    <group position={[29.2, 0, -10]} rotation={[0, 0, 0]} {...props} dispose={null}>
      <mesh
        geometry={nodes.silverRamp.geometry}
        material={materials.bioLabUniqueTexture001}
        position={[2.967, 0.159, 0.564]}
        scale={[1, 1, 1.666]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials.generic}
        position={[-4.037, 0.798, -0.465]}
        scale={[1, 1, 1.013]}
      />
      <mesh geometry={nodes.Floor.geometry} material={materials.BioLabFloor001} position={[-4.037, 0, 6.051]} />
      <mesh geometry={nodes.roof.geometry} material={materials.BioLabRoof001} position={[-4.037, 2.7, 6.051]} />
      <group position={[2.477, 0, 0]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials.bioLabUniqueTexture001} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Decals} />
      </group>
      <mesh geometry={nodes.mainDoor.geometry} material={materials.BioLabTrim001} position={[-3.537, 0.798, 6.04]} />
      <mesh
        geometry={nodes.silverRamp002.geometry}
        material={materials.bioLabUniqueTexture001}
        position={[2.967, 0.159, 0.564]}
        scale={[1, 1, 1.666]}
      />
      <mesh geometry={nodes.mainDoor001.geometry} material={materials.BioLabTrim001} position={[-3.537, 0.798, 6.04]} />
      <mesh
        geometry={nodes.tableSet001002.geometry}
        material={materials.BioLabTrim001}
        position={[2.98, 1.043, 5.639]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.shelfHinge.geometry}
        material={materials.BioLabTrim001}
        position={[2.98, 0.839, 5.639]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.tableSet001008.geometry}
        material={materials.BioLabTrim001}
        position={[2.932, 0.839, 5.639]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.tableSet001009.geometry}
        material={materials.BioLabTrim001}
        position={[2.98, 0.503, 5.639]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.plasticwallPlugRail.geometry}
        material={materials.BioLabTrim001}
        position={[3.011, 1.043, 5.643]}
        scale={[1, 1, 1.013]}
      />
      <mesh geometry={nodes.silverRamp003.geometry} material={materials.Decals} position={[2.477, 0, 0]} />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={materials.generic}
        position={[-4.037, 0.798, -1.362]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.cupboard.geometry}
        material={materials.generic}
        position={[-4.037, 0.798, -1.362]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.generic}
        position={[-4.037, 0.798, -3.124]}
        scale={[1, 1, 1.013]}
      />
      <mesh geometry={nodes.wall.geometry} material={materials.bioLabWall} position={[-3.251, 1.35, 7.051]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.bioLabWall} position={[-4.251, 1.35, 7.051]} />
      <mesh geometry={nodes.Plane002.geometry} material={materials.bioLabWall} position={[-4.458, 1.35, 8.007]} />
      <mesh geometry={nodes.Plane003.geometry} material={materials.bioLabWall} position={[-4.537, 1.35, 7.007]} />
      <mesh geometry={nodes.Plane004.geometry} material={materials.bioLabWall} position={[-4.191, 1.35, -1.155]} />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials.bioLabWall}
        position={[-5.037, 1.35, -5.877]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={materials.bioLabWall}
        position={[3.489, 1.35, 6.551]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={materials.bioLabWall}
        position={[3.82, 1.35, 4.062]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.bioLabWall}
        position={[2.989, 1.35, -4.207]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={materials.bioLabWall}
        position={[0.106, 1.35, -6.377]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh geometry={nodes.Plane010.geometry} material={materials.bioLabWall} position={[4.32, 1.35, 5.637]} />
      <mesh geometry={nodes.Plane011.geometry} material={materials.bioLabWall} position={[1.106, 1.35, -4.207]} />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={materials.bioLabWall}
        position={[3.82, 1.35, 4.062]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={materials.bioLabWall}
        position={[3.489, 1.35, 6.551]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh geometry={nodes.Plane014.geometry} material={materials.bioLabWall} position={[1.106, 1.35, -4.207]} />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={materials.bioLabWall}
        position={[-5.037, 1.35, -5.877]}
        rotation={[0, -1.571, 0]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={materials.bioLabWall}
        position={[3.489, 1.35, 6.551]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.windowLedge.geometry}
        material={materials.generic}
        position={[0.519, 1.35, -6.204]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={materials.generic}
        position={[-0.229, 1.35, -6.204]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.fridgelp001.geometry}
        material={materials['lpMaterial.001']}
        position={[-0.617, 1.161, 3.13]}
      />
      <mesh
        geometry={nodes.fridgelp002.geometry}
        material={materials['lpMaterial.001']}
        position={[-0.617, 1.161, -1.419]}
      />
      <mesh
        geometry={nodes.fridgelp003.geometry}
        material={materials['lpMaterial.001']}
        position={[-2.385, 1.161, 0.823]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.fridgelp004.geometry}
        material={materials['lpMaterial.001']}
        position={[-2.385, 1.161, -2.208]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.mountedWallCabinet001.geometry}
        material={materials.BioLabTrim001}
        position={[-0.007, 1.702, 6.6]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <group position={[-1.94, 1.683, 6.724]} rotation={[Math.PI, -0.175, Math.PI]} scale={0.088}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials.Brush_Metal} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials.Decals} />
      </group>
      <mesh
        geometry={nodes.roof002.geometry}
        material={materials.BioLabRoofDecal001}
        position={[-4.034, 2.692, 5.384]}
      />
      <mesh
        geometry={nodes.roof003.geometry}
        material={materials.BioLabRoofDecal001}
        position={[-0.7, 2.692, 6.717]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.roof004.geometry}
        material={materials.BioLabRoofDecal001}
        position={[-4.034, 2.692, 6.051]}
      />
      <mesh geometry={nodes.roof005.geometry} material={materials.BioLabRoofDecal001} position={[1.3, 2.692, 5.384]} />
      <mesh
        geometry={nodes.Decal_silverRamp002.geometry}
        material={materials.Decals}
        position={[2.121, 0.009, -2.148]}
        scale={[1, 1, 1.452]}
      />
      <mesh
        geometry={nodes.Prop_Cube008.geometry}
        material={materials.Brush_Metal}
        position={[1.824, 0.532, 2.091]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.tank.geometry}
        material={materials.Brush_Metal}
        position={[2.869, 1.445, 2.138]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Prop_Cube007.geometry}
        material={materials.generic}
        position={[2.853, 1.461, 2.138]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={materials['Material.003']}
        position={[2.522, 1.575, 1.625]}
        scale={[0.071, 0.071, 0.079]}
      />
      <mesh
        geometry={nodes.Prop_Cube016.geometry}
        material={materials.Brush_Metal}
        position={[2.793, 1.484, 2.031]}
        scale={[0.115, 0.115, 0.127]}
      >
        <mesh
          geometry={nodes.Prop_Decal_Cube005.geometry}
          material={materials.Decals}
          position={[-3.392, 2.153, 2.097]}
          scale={[1, 1, 0.773]}
        />
      </mesh>
      <mesh
        geometry={nodes.Decal_Cube018.geometry}
        material={materials.Decals}
        position={[2.959, 1.523, 2.138]}
        scale={[0.129, 0.129, 0.144]}
      />
      <mesh
        geometry={nodes.Decal_Cube017.geometry}
        material={materials.Decals}
        position={[2.649, 2.608, 1.97]}
        rotation={[0, 0.373, 0]}
        scale={1.225}
      />
      <mesh geometry={nodes.Decal_Cube019.geometry} material={materials.Decals} position={[2.474, 1.5, 1.625]}>
        <mesh
          geometry={nodes.Cutter.geometry}
          material={materials['default']}
          position={[0.016, 0.289, 0.051]}
          rotation={[Math.PI, 0, Math.PI / 2]}
        />
      </mesh>
      <mesh
        geometry={nodes.Decal_Cube026.geometry}
        material={materials.Decals}
        position={[1.607, 0.334, 2.091]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Decal_Cube027.geometry}
        material={materials.Decals}
        position={[2.791, 1.631, 2.293]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube028.geometry}
        material={materials.Decals}
        position={[2.791, 1.554, 2.293]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube029.geometry}
        material={materials.Decals}
        position={[3.098, 1.554, 2.293]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube030.geometry}
        material={materials.Decals}
        position={[3.098, 1.623, 2.293]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube031.geometry}
        material={materials.Decals}
        position={[2.766, 1.579, 2.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.913}
      />
      <mesh
        geometry={nodes.Decal_Cube032.geometry}
        material={materials.Decals}
        position={[3.109, 1.516, 2.253]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.321}
      />
      <mesh
        geometry={nodes.Decal_Cube033.geometry}
        material={materials.Decals}
        position={[3.109, 1.402, 2.253]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.321}
      />
      <mesh
        geometry={nodes.Decal_Cube034.geometry}
        material={materials.Decals}
        position={[2.546, 1.774, 2.424]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.307}
      />
      <mesh
        geometry={nodes.Decal_Cube035.geometry}
        material={materials.Decals}
        position={[2.546, 1.603, 2.424]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.307}
      />
      <mesh
        geometry={nodes.Decal_Cube036.geometry}
        material={materials.Decals}
        position={[2.577, 1.776, 2.411]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Decal_Cube037.geometry}
        material={materials.Decals}
        position={[2.577, 1.605, 2.411]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Decal_Cube038.geometry}
        material={materials.Decals}
        position={[2.577, 1.605, 2.204]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Decal_Cube039.geometry}
        material={materials.Decals}
        position={[2.577, 1.778, 2.204]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.194}
      />
      <mesh
        geometry={nodes.Decal_Cube001.geometry}
        material={materials.Decals}
        position={[2.649, 2.608, -0.278]}
        rotation={[0, 0.373, 0]}
        scale={1.225}
      />
      <mesh geometry={nodes.Decal_Cube002.geometry} material={materials.Decals} position={[2.474, 1.5, -0.623]} />
      <mesh
        geometry={nodes.Prop_Cube019.geometry}
        material={materials.generic}
        position={[2.853, 1.461, -0.066]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Prop_Cube021.geometry}
        material={materials.Brush_Metal}
        position={[2.793, 1.484, -0.173]}
        scale={[0.115, 0.115, 0.127]}
      >
        <mesh
          geometry={nodes.Decal_Cube003.geometry}
          material={materials.Decals}
          position={[-3.392, 2.153, 2.097]}
          scale={[1, 1, 0.773]}
        />
      </mesh>
      <mesh
        geometry={nodes.Decal_Cube004.geometry}
        material={materials.Decals}
        position={[2.791, 1.631, 0.089]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube006.geometry}
        material={materials.Decals}
        position={[2.791, 1.554, 0.089]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube007.geometry}
        material={materials.Decals}
        position={[3.098, 1.554, 0.089]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube008.geometry}
        material={materials.Decals}
        position={[3.098, 1.623, 0.089]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.477}
      />
      <mesh
        geometry={nodes.Decal_Cube009.geometry}
        material={materials.Decals}
        position={[2.766, 1.579, -0.164]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.913}
      />
      <mesh
        geometry={nodes.Decal_Cube010.geometry}
        material={materials.Decals}
        position={[3.109, 1.516, 0.049]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.321}
      />
      <mesh
        geometry={nodes.Decal_Cube011.geometry}
        material={materials.Decals}
        position={[3.109, 1.402, 0.049]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.321}
      />
      <mesh
        geometry={nodes.Decal_Cube012.geometry}
        material={materials.Decals}
        position={[2.546, 1.774, 0.22]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.307}
      />
      <mesh
        geometry={nodes.Decal_Cube013.geometry}
        material={materials.Decals}
        position={[2.546, 1.603, 0.22]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={0.307}
      />
      <mesh
        geometry={nodes.Prop_Cube023.geometry}
        material={materials.Brush_Metal}
        position={[1.824, 0.532, -0.14]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Decal_Cube014.geometry}
        material={materials.Decals}
        position={[1.607, 0.334, -0.14]}
        scale={[0.115, 0.115, 0.127]}
      />
      <mesh
        geometry={nodes.Decal_Cube015.geometry}
        material={materials.Decals}
        position={[2.402, 1.758, 2.238]}
        scale={0.244}
      />
      <group position={[2.529, 2.366, 1.65]} rotation={[0, 0.373, 0]} scale={0.62}>
        <mesh geometry={nodes.Vert013.geometry} material={materials['Brush_Metal.006']} />
        <mesh geometry={nodes.Vert013_1.geometry} material={materials['generic.001']} />
        <mesh geometry={nodes.Vert013_2.geometry} material={materials['generic.002']} />
        <mesh geometry={nodes.Vert013_3.geometry} material={materials['Brush_Metal.005']} />
        <mesh geometry={nodes.Vert013_4.geometry} material={materials['generic.003']} />
      </group>
      <group position={[2.529, 2.366, -0.593]} rotation={[0, 0.373, 0]} scale={0.62}>
        <mesh geometry={nodes.Vert013.geometry} material={materials['Brush_Metal.006']} />
        <mesh geometry={nodes.Vert013_1.geometry} material={materials['generic.001']} />
        <mesh geometry={nodes.Vert013_2.geometry} material={materials['generic.002']} />
        <mesh geometry={nodes.Vert013_3.geometry} material={materials['Brush_Metal.005']} />
        <mesh geometry={nodes.Vert013_4.geometry} material={materials['generic.003']} />
      </group>
      <mesh
        geometry={nodes.Prop_Vert010.geometry}
        material={materials.generic}
        position={[2.969, 0.833, 1.328]}
        scale={5.389}
      />
      <mesh geometry={nodes.Prop_Vert003.geometry} material={materials.Brush_Metal} position={[2.937, 1.304, -0.852]} />
      <mesh
        geometry={nodes.Prop_Vert004.geometry}
        material={materials.generic}
        position={[3.169, 0.833, 0.84]}
        scale={5.389}
      />
      <mesh geometry={nodes.Prop_cable.geometry} material={materials.generic} position={[2.666, 1.583, 2.207]} />
      <mesh geometry={nodes.Prop_cable001.geometry} material={materials.generic} position={[2.666, 1.583, 0.003]} />
      <mesh
        geometry={nodes.tableSet001001.geometry}
        material={materials.BioLabTrim001}
        position={[3.011, 1.043, 5.639]}
      />
      <mesh
        geometry={nodes.TableSetCounter.geometry}
        material={materials.BioLabTrim001}
        position={[3.011, 1.043, 5.639]}
        scale={[1, 1, 1.013]}
      />
      <mesh
        geometry={nodes.tableSet001004.geometry}
        material={materials.BioLabTrim001}
        position={[3.011, 1.043, 5.639]}
      />
      <mesh
        geometry={nodes.tableSet001005.geometry}
        material={materials.BioLabTrim001}
        position={[5.456, 1.043, 5.639]}
      />
      <mesh
        geometry={nodes.tableSet001006.geometry}
        material={materials.BioLabTrim001}
        position={[5.456, 1.043, 5.639]}
      />
      <mesh
        geometry={nodes.tableSet001011.geometry}
        material={materials.BioLabTrim001}
        position={[-3.641, 1.043, 4.385]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.tableSet001012.geometry}
        material={materials.BioLabTrim001}
        position={[-3.641, 1.043, 4.385]}
        rotation={[0, -Math.PI / 2, 0]}
      />
      <mesh geometry={nodes.Plane017.geometry} material={materials.Brush_Metal} position={[1.106, 1.35, -4.484]} />
      <mesh geometry={nodes.Plane018.geometry} material={materials.Brush_Metal} position={[1.106, 1.35, -4.484]} />
      <mesh geometry={nodes.Plane019.geometry} material={materials.Brush_Metal} position={[1.148, 1.349, -4.305]} />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={materials.Brush_Metal}
        position={[1.729, 2.199, -4.163]}
        scale={0.751}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={materials.Brush_Metal}
        position={[1.794, 2.191, -4.13]}
        rotation={[0, -0.969, 0]}
        scale={0.751}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={materials.Brush_Metal}
        position={[1.387, 1.094, -4.185]}
        scale={0.467}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.Brush_Metal}
        position={[1.387, 1.157, -4.176]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.011}
      />
    </group>
  )
}

useGLTF.preload('/Biolab4.glb')
