/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect } from 'react'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function Tmobile(props) {
  const gltf = useLoader(GLTFLoader, '/assets/2023-04-27/v007/r6.glb')

  // Add error handling
  useEffect(() => {
    if (!gltf) {
      console.error('Failed to load Tmobile model')
      return
    }
    console.log('Loaded model:', gltf)
    if (gltf.scene) {
      console.log('Scene nodes:', gltf.scene.children)
      console.log('Materials:', gltf.materials)
    }
  }, [gltf])

  return (
    <group position={[0, -2, 0]} {...props}>
      <primitive object={gltf.scene} scale={[1, 1, 1]} rotation={[0, 0, 0]} />
    </group>
  )
}
